server:
  port: 8080

spring:

  # profile settings
  config:
    activate:
      on-profile: dev

  # mariadb settings
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate: 
      # create, create-drop, update, none
      ddl-auto: none
      # 콘솔출력
    show-sql: true     
    properties:
      hibernate:
        # h2
        # dialect: org.hibernate.dialect.H2Dialect
        # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true 
  
  # redis
  # docker run -d --name redis-container -p 6379:6379 redis:7.2
  # docker exec -it redis-container redis-cli 
  # ping
  # docker run -d --name redis-insight -p 8001:5540 redis/redisinsight:latest
  # http://localhost:8001
  # Host: redis 또는 host.docker.internal , port: 6379

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 
      timeout: 6000ms

  # mybatis settings
  # mybatis:
  #     mapper-locations: /mappers/**/*Mapper.xml
  #     config-location:  classpath:/mappers/config/mybatis-config.xml 


jwt:
  secret: ${JWT_SECURITY_KEY}
